### ISSUE TITLE
Deploying Java-Evaluator

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/deploy_docker#1]
https://github.com/KA226-COVID/deploy_docker/blob/d82c4586196493c9cd47b498dd1c031089a6b36b/.env.example#L23

To allow Turkish testers propose and solve exercises, we must also deploy [Java-Evaluator](https://github.com/KA226-COVID/java-evaluator) . It's very similar to XML-evaluator because it's basically a copy of [xml-evaluator](https://github.com/KA226-COVID/xml-evaluator) but for Java exercises. Then it needs similar environment variables.

**Comment by brdebr** [comment]
For this is pending add java into the java-validator docker machine and test it with java exercises,
also it's needed to add the java language at the codetest config.php
