### ISSUE TITLE
TSUGI_GOOGLE_CLIENT_SECRET

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/deploy_docker#11]
Se mantiene el TSUGI_GOOGLE_CLIENT_ID en lugar de TSUGI_GOOGLE_CLIENT_SECRET
https://github.com/KA226-COVID/deploy_docker/blob/fd6bc2b59354bcac65e36ac3f53dac5b984dd7c7/tsugi/config_tsugi_docker.php#L212

**Comment by frasese** [comment]
Solved in 320a3b2be545cba7499c46dc9dba6b4d50cfe89f
