### ISSUE TITLE
env var duplicated

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/deploy_docker#4]
https://github.com/KA226-COVID/deploy_docker/blob/a58a7208508a363bbd3aa525b3adcec53803556e/.env.example#L27

**Comment by brdebr** [comment]
This was fixed at [509a2e](https://github.com/KA226-COVID/deploy_docker/commit/509a2e1d6c3b9d78d4ac89f7e619f4eddb38ee6c)
